#ifndef _CONFIG_h
#define _CONFIG_h

#define SERIAL_SPEED			115200
#define SCALEDATAPIN_MAIN		25
#define SCALECLKPIN_MAIN		26
#define SCALEDATAPIN_LEFT	
#define SCALECLKPIN_LEFT
#define SCALEDATAPIN_RIGHT	
#define SCALECLKPIN_RIGHT

#define SCALEGAIN_MAIN			128
#define SCALEGAIN_LEFT			128
#define SCALEGAIN_RIGHT			128

#define SCALEFACTOR_MAIN		199.21
#define SCALEFACTOR_LEFT		199.21
#define SCALEFACTOR_RIGHT		199.21

#define SCALENUMBEROFAVERAGECYCLES	5
#endif